version: '3'

services:
  database:
    container_name: test_database_minitwit
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "superuser"
      POSTGRES_PASSWORD: "su"
      POSTGRES_DB: "database_minitwit"
    ports:
      - "5555:5432"
    volumes:
      - "test-database-data:/var/lib/postgresql/data/"
  
  web:
    container_name: test_web_minitwit
    image: andersstendevad/minitwit_web:latest
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - "database"
      - "api"
    ports:
      - "8000:8000"

  api:
    container_name: test_api_minitwit
    image: andersstendevad/minitwit_api:latest
    command: ./start.sh
    depends_on:
      - "database"
      - "prometheus"
      - "grafana"
    ports:
      - "8080:8080"

  grafana:
    container_name: grafana
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana  

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  elasticsearch:
    container_name: test_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - test-elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9000

  kibana:
    container_name: test_kibana
    image: docker.elastic.co/kibana/kibana:7.9.0
    environment:
      elasticsearch.hosts: '["elasticsearch:9000"]'
    ports:
      - 5601:5601

  filebeat:
    container_name: test_filebeat
    image: docker.elastic.co/beats/filebeat:7.9.0
    user: root
    volumes:
      - ./test_filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  test-database-data:
  test-elasticsearch-data:
  grafana-data:
  prometheus-data:
