{
 "title": "Minitwit",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minitwit_cpu_load_percent{alias=\"api\"}",
       "legendFormat": "API"
      }
     ]
    },
    {
     "title": "UPTIME",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 7, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time()-process_start_time_seconds{alias=\"api\", instance=\"api:8080\", job=\"api_monitoring\"}"
      }
     ]
    },
    {
     "title": "Noise",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {}
     ]
    }
   ]
  },
  { "title": "API Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "text",
   "description": "Note",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "options": {
    "content": "# API Metrics\n\nRelative activity on each of the four API endpoints\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_bucket{alias=\"api\", instance=\"api:8080\", job=\"api_monitoring\", le=\"+Inf\", method=\"GET\", view=\"minitwit.views.LatestView\"}[2m])",
     "legendFormat": "/latest"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_bucket{le=\"+Inf\",method=\"POST\",view=\"minitwit.views.UserMessagesView\"}[2m])",
     "legendFormat": "/msgs"
    }
   ]
  },
  {
   "title": "Follow Acticity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_bucket{le=\"+Inf\",method=\"POST\",view=\"minitwit.views.UserFollowersView\"}[2m])",
     "legendFormat": "/fllws"
    }
   ]
  },
  {
   "title": "Registration Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_bucket{le=\"+Inf\",method=\"POST\",view=\"minitwit.views.RegistrationView\"}[2m])",
     "legendFormat": "/register"
    }
   ]
  },
  { "title": "Frontend Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Public Timeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_bucket{alias=\"web\", instance=\"web:8000\", job=\"web_monitoring\", le=\"75.0\", method=\"GET\", view=\"public_timeline\"}[1m])",
     "legendFormat": "Public Timeline"
    }
   ]
  },
  {
   "title": "Profile Visits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_profile_visits_total[2m])",
     "legendFormat": "Public Timeline"
    }
   ]
  },
  {
   "title": "Total Sign-Ins",
   "type": "stat",
   "description": "Total sign-Ins in past 24 hours",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(total_sign_ins_total[1d])"
    }
   ]
  },
  { "title": "Business Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total user",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "users" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM profiles" }
   ]
  },
  {
   "title": "New Users Today",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM profiles\nWHERE date_joined > now() - interval '1 days'\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Total Messages Posted Today",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM messages\nWHERE\n  publication_date > now() - interval '1 day'\nORDER BY 1\n"
    }
   ]
  }
 ]
}