filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-elastic-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.image.name: test_filebeat
        - equals:
            container.image.name: test_elasticsearch
        - equals:
            container.image.name: test_kibana
    - index: "filebeat-minitwit-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
          - equals:
              container.image.name: test_api_minitwit
          - equals:
              container.image.name: test_web_minitwit
    - index: "filebeat-ngix-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.equals:
        container.image.name: nginx

logging.json: true
logging.metrics.enabled: false


