apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f test-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: filebeat
  name: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: filebeat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f test-compose.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: filebeat
    spec:
      containers:
        - image: docker.elastic.co/beats/filebeat:7.2.0
          name: test-filebeat
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/filebeat/filebeat.yml
              name: filebeat-claim0
              readOnly: true
            - mountPath: /var/lib/docker
              name: filebeat-claim1
              readOnly: true
            - mountPath: /var/run/docker.sock
              name: filebeat-claim2
      restartPolicy: Always
      volumes:
        - name: filebeat-claim0
          persistentVolumeClaim:
            claimName: filebeat-claim0
            readOnly: true
        - name: filebeat-claim1
          persistentVolumeClaim:
            claimName: filebeat-claim1
            readOnly: true
        - name: filebeat-claim2
          persistentVolumeClaim:
            claimName: filebeat-claim2
status: {}
